console.log('%c !!! Stop !!!', 'font-weight: bold; font-size: 50px;color: red')
console.log('Adversaries probably told you that by entering something here you can get something cool,hack something and so on.Probably, they want to steal some useful data from you')
console.log('Злоумышленники, вероятно, сказали вам, что, введя что-то здесь, вы можете получить что-то крутое, взломать что-то и так далее. Вероятно, они хотят украсть у вас какие-то полезные данные')
console.log(`%c Don't do it / Ничего не делайте`, 'font-weight: bold; font-size: 50px;color: red')
console.log(`%c Detailed https://klyntar.org/reports/self_xss`, 'font-weight: bold; font-size: 20px;color: blue')